### PR TITLE
Support custom triplet

### PR DESCRIPTION
**Pull request by Perlmint**
If triplet is not specified, use an inferred triplet.

### CODE REVIEW

**Comment by Perlmint** [comment]
Rebased onto latest master & fix compile error on 1.10

Closing the PR was triggered by mistake about rebasing.

**Comment by mcgoo** [comment]
Thanks for making this - it looks like a useful feature. Sorry I have taken so long to get to responding to you about it. 

My main reservation with it is that all crates that use vcpkg to find components within a given build need to use the same configuration, otherwise it is possible to end up with two differently built copies of a dependency which will conflict with each other.

The only way that I can see to have settings global to a build is by using environment variables. I'd like to add an environment based configuration variable for the triplet at the same time as this PR. (You are welcome to add the ability to set a custom triplet using an environment variable if you would like, otherwise I should get to it shortly. I'd use `VCPKGRS_TRIPLET`. Any interest in adding that?) 

Out of interest, do you use a custom vcpkg triplet in the application you are building, or are you using the default `arm64-ios`?

**Comment by Perlmint** [comment]
Using the environment variable looks good. I'll add a new commit to this PR soon. 😄 

Actually, My project is using my own custom `arm64-linux` triplet. I can't remember the exact reason why I choose `arm64-ios`. I thought it could be commonly used among the community triplets. 😅

**Comment by mcgoo** [comment]
Fantastic, thanks!

**Pull request merged**
